### ISSUE TITLE
Update current task flow and draft alternatives based on field visit

### ISSUE THREAD

**Issue by cmajel** [18F/USFS-timber-permitting#35]
**Background**
This issue is to brainstorm alternative task flows for getting a fuelwood permit based on what we learned during our field visit, and our service blueprint (#31).

Helpful resources
* [Our current task flow model](https://app.mural.co/t/gsa6/m/gsa6/1561135937859/c5bc56efbc767d9dc04de2aa8142a8b6a3205d41), which may need updating based on our field visit
* [Our proposed task flow model](https://app.mural.co/t/gsa6/m/gsa6/1571674517069/a0143a1bc7c4481453a6eacd5f8dc037523b7e56) prior to our field visit. 

**Acceptance criteria** 
- [ ] 
- [ ] 

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  
- [ ]

**Comment by cmajel** [comment]
@MelissaBraxton @tram is this what you're thinking with #31 ? Or should this be its own task?

**Comment by MelissaBraxton** [comment]
@cmajel - I think we may have tackled this this sprint. Can you take a crack at refining this card?

**Comment by cmajel** [comment]
@MelissaBraxton my thinking when I wrote was this is when we'd define an alternative task flow to inform the next round of prototyping.

I think our immediate needs will be covered when we revise design hypotheses (#38) and this new card to determine what prototypes we need next (#48). I could see us doing a more comprehensive service blueprint for an alternative service model in a few weeks after we do another round of testing, but I agree that we can close this for now.
